language: julia
os:
  - linux
julia:
  - 0.6
addons:
    apt:
        packages:
            - hdf5-tools
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/806e21f217bd85b785ad
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
before_script:
    - julia --color=yes -e 'Pkg.clone("https://github.com/JuliaFEM/PkgTestSuite.jl.git")'
    - julia --color=yes -e 'using PkgTestSuite; init()'
script:
    - julia --color=yes -e 'using PkgTestSuite; test()'
after_success:
    - julia --color=yes -e 'using PkgTestSuite; deploy()'
